import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";
import accentGuard from "./src/client/theme/eslint-accent-guard.mjs";

const SINK_MESSAGE = "Sentry, metrics and the audit log are reached only through src/worker/auth/observe.ts.";
const OBSERVE_MESSAGE = "Use reportError / count / record from src/worker/auth/observe.ts.";
// The two worker-wide syntax rules. A later block's `no-restricted-syntax` REPLACES an earlier
// one for the files it matches, so every block that sets the rule for worker files repeats these.
const NO_RAW_WAIT_UNTIL = {
  selector: "CallExpression[callee.property.name='waitUntil']",
  message: "Use defer(c, promise) from services/request-context (or bg.defer / deps.defer).",
};
const NO_RAW_JSON_BODY = {
  selector: "CallExpression[callee.property.name='json'][callee.object.property.name='req']",
  message: "Use jsonBody(c) from services/body: c.req.json() answers a malformed body with a 500.",
};

export default tseslint.config(
  {
    ignores: [
      ".claude/**",
      ".remember/**",
      "dist/**",
      ".wrangler/**",
      "holdfast-plan/**",
      "node_modules/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      // Generated by `npm run cf-typegen`.
      "src/worker/env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // The SPA.
    files: ["src/client/**/*.{ts,tsx}"],
    languageOptions: { globals: globals.browser },
    plugins: { "react-hooks": reactHooks, "react-refresh": reactRefresh },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
    },
  },
  {
    // The activity colour and `palette.primary` belong to the theme and to the four components
    // that show activity; everywhere else in the SPA naming them is an error. The rule itself
    // decides which files are exempt (src/client/theme/eslint-accent-guard.mjs).
    files: ["src/client/**/*.{ts,tsx}"],
    plugins: { holdfast: accentGuard },
    rules: { "holdfast/accent-guard": "error" },
  },
  {
    // Plain scripts served as they are (the first-paint colour-scheme script).
    files: ["public/**/*.js"],
    languageOptions: { globals: globals.browser, sourceType: "script" },
  },
  {
    // Deferred work goes through defer(c, p): a raw waitUntil is not awaited before the database
    // pool closes. Only the request context and the Worker entry may call it.
    // A JSON body is read with jsonBody(c): c.req.json() turns a malformed body into a 500.
    files: ["src/worker/**/*.ts"],
    ignores: ["src/worker/services/body.ts", "src/worker/services/request-context.ts", "src/worker/index.ts"],
    rules: {
      "no-restricted-syntax": ["error", NO_RAW_WAIT_UNTIL, NO_RAW_JSON_BODY],
    },
  },
  {
    // In the two files that may call waitUntil, the body rule still applies.
    files: ["src/worker/services/request-context.ts", "src/worker/index.ts"],
    rules: {
      "no-restricted-syntax": ["error", NO_RAW_JSON_BODY],
    },
  },
  {
    // The auth layer has ONE exit to each sink: Sentry, the metrics and the audit log are reached
    // only through auth/observe.ts, the console only through auth/logger.ts — both redact what
    // they are given. Anything else in the layer that names a sink directly is an error.
    files: [
      "src/worker/auth/**/*.ts",
      "src/worker/routes/{auth,signup-intent,invites,pending-email,account-lifecycle}.ts",
      "src/worker/services/{email,signup-policy,account-state}.ts",
    ],
    ignores: ["src/worker/auth/observe.ts", "src/worker/auth/logger.ts"],
    rules: {
      "no-console": "error",
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            { regex: "(^|/)sentry$", message: SINK_MESSAGE },
            { regex: "^@sentry/", message: SINK_MESSAGE },
            { regex: "(^\\.\\./services/|^\\./)metrics$", message: SINK_MESSAGE },
            { regex: "^\\.\\./services/audit$", message: SINK_MESSAGE },
          ],
        },
      ],
      "no-restricted-syntax": [
        "error",
        NO_RAW_WAIT_UNTIL,
        NO_RAW_JSON_BODY,
        {
          selector:
            "CallExpression[callee.name=/^(captureError|captureException|captureMessage|addBreadcrumb|setContext|setTag|setTags|setExtra|setExtras|setUser|writeMetric|insertAudit)$/]",
          message: OBSERVE_MESSAGE,
        },
        {
          selector:
            "CallExpression[callee.property.name=/^(captureException|captureMessage|addBreadcrumb|setContext|setTag|setTags|setExtra|setExtras|setUser|writeDataPoint)$/]",
          message: OBSERVE_MESSAGE,
        },
      ],
    },
  },
  {
    // In src/worker/services, "./audit" is the audit SERVICE (in src/worker/auth it is the
    // layer's own file), so there it is a sink too.
    files: ["src/worker/services/{email,signup-policy,account-state}.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            { regex: "(^|/)sentry$", message: SINK_MESSAGE },
            { regex: "^@sentry/", message: SINK_MESSAGE },
            { regex: "^\\./(metrics|audit)$", message: SINK_MESSAGE },
          ],
        },
      ],
    },
  },
  // observe.ts is the exit to Sentry, metrics and the audit log — not to the console.
  { files: ["src/worker/auth/observe.ts"], rules: { "no-console": "error" } },
  {
    // Node-side files: tool configs, scripts and the placeholder container server.
    files: ["*.config.{js,ts,mjs}", "scripts/**/*.{js,mjs,ts}", "containers/**/*.{js,mjs}"],
    languageOptions: { globals: globals.node },
  },
);
