import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";
import accentGuard from "./src/client/theme/eslint-accent-guard.mjs";

export default tseslint.config(
  {
    ignores: [
      ".claude/**",
      ".remember/**",
      "dist/**",
      ".wrangler/**",
      "holdfast-plan/**",
      "node_modules/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      // Generated by `npm run cf-typegen`.
      "src/worker/env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // The SPA.
    files: ["src/client/**/*.{ts,tsx}"],
    languageOptions: { globals: globals.browser },
    plugins: { "react-hooks": reactHooks, "react-refresh": reactRefresh },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
    },
  },
  {
    // The activity colour and `palette.primary` belong to the theme and to the four components
    // that show activity; everywhere else in the SPA naming them is an error. The rule itself
    // decides which files are exempt (src/client/theme/eslint-accent-guard.mjs).
    files: ["src/client/**/*.{ts,tsx}"],
    plugins: { holdfast: accentGuard },
    rules: { "holdfast/accent-guard": "error" },
  },
  {
    // Plain scripts served as they are (the first-paint colour-scheme script).
    files: ["public/**/*.js"],
    languageOptions: { globals: globals.browser, sourceType: "script" },
  },
  {
    // Deferred work goes through defer(c, p): a raw waitUntil is not awaited before the database
    // pool closes. Only the request context and the Worker entry may call it.
    // A JSON body is read with jsonBody(c): c.req.json() turns a malformed body into a 500.
    files: ["src/worker/**/*.ts"],
    ignores: ["src/worker/services/body.ts", "src/worker/services/request-context.ts", "src/worker/index.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "CallExpression[callee.property.name='waitUntil']",
          message: "Use defer(c, promise) from services/request-context (or bg.defer / deps.defer).",
        },
        {
          selector: "CallExpression[callee.property.name='json'][callee.object.property.name='req']",
          message: "Use jsonBody(c) from services/body: c.req.json() answers a malformed body with a 500.",
        },
      ],
    },
  },
  {
    // In the two files that may call waitUntil, the body rule still applies.
    files: ["src/worker/services/request-context.ts", "src/worker/index.ts"],
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector: "CallExpression[callee.property.name='json'][callee.object.property.name='req']",
          message: "Use jsonBody(c) from services/body: c.req.json() answers a malformed body with a 500.",
        },
      ],
    },
  },
  {
    // Node-side files: tool configs, scripts and the placeholder container server.
    files: ["*.config.{js,ts,mjs}", "scripts/**/*.{js,mjs,ts}", "containers/**/*.{js,mjs}"],
    languageOptions: { globals: globals.node },
  },
);
