import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      ".claude/**",
      ".remember/**",
      "dist/**",
      ".wrangler/**",
      "holdfast-plan/**",
      "node_modules/**",
      "coverage/**",
      "playwright-report/**",
      "test-results/**",
      // Generated by `npm run cf-typegen`.
      "src/worker/env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    // The SPA.
    files: ["src/client/**/*.{ts,tsx}"],
    languageOptions: { globals: globals.browser },
    plugins: { "react-hooks": reactHooks, "react-refresh": reactRefresh },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
    },
  },
  {
    // Node-side files: tool configs, scripts and the placeholder container server.
    files: ["*.config.{js,ts,mjs}", "scripts/**/*.{js,mjs,ts}", "containers/**/*.{js,mjs}"],
    languageOptions: { globals: globals.node },
  },
);
