/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false --strict-vars=false src/worker/env.d.ts` (hash: f486e1e15bab33397daae2d92f1779ad)
interface __BaseEnv_Env {
	FILES: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	METRICS: AnalyticsEngineDataset;
	SCAN_QUEUE: Queue;
	RL_AUTH: RateLimit;
	RL_API: RateLimit;
	RL_FILES: RateLimit;
	RL_LINKS: RateLimit;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	SIGNUP_MODE: string;
	SIGNUP_ALLOWED_DOMAINS: string;
	QUOTA_BYTES: string;
	MAX_FILE_BYTES: string;
	PART_BYTES: string;
	CEIL_USER_BYTES_DAY: string;
	CEIL_LINK_BYTES_DAY: string;
	CEIL_LINK_DOWNLOADS_DAY: string;
	CEIL_IP_BYTES_DAY: string;
	CEIL_UPLOAD_BYTES_DAY: string;
	CEIL_UPLOAD_COUNT_DAY: string;
	CEIL_EDITOR_UPLOAD_BYTES_DAY: string;
	CEIL_TRANSFORMS_DAY: string;
	CEIL_SHARES_DAY: string;
	CEIL_LINKS_DAY: string;
	NEW_ACCOUNT_DAYS: string;
	NEW_ACCOUNT_FACTOR: string;
	NEW_ACCOUNT_MAX_LINKS: string;
	PHOTODNA_ENABLED: string;
	SENTRY_ENVIRONMENT: string;
	CF_ACCOUNT_ID: string;
	TERMS_VERSION: string;
	BETTER_AUTH_SECRET: string;
	FILES_TOKEN_SECRET: string;
	IP_ENC_KEY: string;
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	RESEND_API_KEY: string;
	SENTRY_DSN: string;
	ADMIN_EMAILS: string;
	PHOTODNA_SUBSCRIPTION_KEY?: string;
	CF_ANALYTICS_TOKEN?: string;
	TURNSTILE_SITEKEY: string;
	TURNSTILE_SECRET: string;
	APP_ORIGIN: string;
	FILES_ORIGIN: string;
	EMAIL_TRANSPORT: string;
	SCAN_STUB: string;
	SENTRY_DSN_WEB: string;
	SCANNER: DurableObjectNamespace<import("./index").ScannerContainer>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "ScannerContainer";
	}
	interface ProductionEnv {
		FILES: R2Bucket;
		HYPERDRIVE: Hyperdrive;
		METRICS: AnalyticsEngineDataset;
		SCAN_QUEUE: Queue;
		RL_AUTH: RateLimit;
		RL_API: RateLimit;
		RL_FILES: RateLimit;
		RL_LINKS: RateLimit;
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
		SIGNUP_MODE: string;
		SIGNUP_ALLOWED_DOMAINS: string;
		QUOTA_BYTES: string;
		MAX_FILE_BYTES: string;
		PART_BYTES: string;
		CEIL_USER_BYTES_DAY: string;
		CEIL_LINK_BYTES_DAY: string;
		CEIL_LINK_DOWNLOADS_DAY: string;
		CEIL_IP_BYTES_DAY: string;
		CEIL_UPLOAD_BYTES_DAY: string;
		CEIL_UPLOAD_COUNT_DAY: string;
		CEIL_EDITOR_UPLOAD_BYTES_DAY: string;
		CEIL_TRANSFORMS_DAY: string;
		CEIL_SHARES_DAY: string;
		CEIL_LINKS_DAY: string;
		NEW_ACCOUNT_DAYS: string;
		NEW_ACCOUNT_FACTOR: string;
		NEW_ACCOUNT_MAX_LINKS: string;
		PHOTODNA_ENABLED: string;
		SENTRY_ENVIRONMENT: string;
		CF_ACCOUNT_ID: string;
		TERMS_VERSION: string;
		BETTER_AUTH_SECRET: string;
		FILES_TOKEN_SECRET: string;
		IP_ENC_KEY: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		RESEND_API_KEY: string;
		SENTRY_DSN: string;
		ADMIN_EMAILS: string;
		PHOTODNA_SUBSCRIPTION_KEY?: string;
		CF_ANALYTICS_TOKEN?: string;
		TURNSTILE_SITEKEY: string;
		TURNSTILE_SECRET: string;
		APP_ORIGIN: string;
		FILES_ORIGIN: string;
		EMAIL_TRANSPORT: string;
		SCAN_STUB: string;
		SENTRY_DSN_WEB: string;
		SCANNER: DurableObjectNamespace<import("./index").ScannerContainer>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SIGNUP_MODE" | "SIGNUP_ALLOWED_DOMAINS" | "QUOTA_BYTES" | "MAX_FILE_BYTES" | "PART_BYTES" | "CEIL_USER_BYTES_DAY" | "CEIL_LINK_BYTES_DAY" | "CEIL_LINK_DOWNLOADS_DAY" | "CEIL_IP_BYTES_DAY" | "CEIL_UPLOAD_BYTES_DAY" | "CEIL_UPLOAD_COUNT_DAY" | "CEIL_EDITOR_UPLOAD_BYTES_DAY" | "CEIL_TRANSFORMS_DAY" | "CEIL_SHARES_DAY" | "CEIL_LINKS_DAY" | "NEW_ACCOUNT_DAYS" | "NEW_ACCOUNT_FACTOR" | "NEW_ACCOUNT_MAX_LINKS" | "PHOTODNA_ENABLED" | "SENTRY_ENVIRONMENT" | "CF_ACCOUNT_ID" | "TERMS_VERSION" | "BETTER_AUTH_SECRET" | "FILES_TOKEN_SECRET" | "IP_ENC_KEY" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "RESEND_API_KEY" | "SENTRY_DSN" | "ADMIN_EMAILS" | "PHOTODNA_SUBSCRIPTION_KEY" | "CF_ANALYTICS_TOKEN" | "TURNSTILE_SITEKEY" | "TURNSTILE_SECRET" | "APP_ORIGIN" | "FILES_ORIGIN" | "EMAIL_TRANSPORT" | "SCAN_STUB" | "SENTRY_DSN_WEB">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}