// The English catalogue. Every user-visible string of the shell goes through `t()` in i18n.ts.
// Voice: plain and exact. Short declaratives, numbers in user units, no exclamation marks; an
// error says what happened and what to do.
export const en = {
  "app.name": "Holdfast",
  "app.skip": "Skip to content",
  "app.loading": "Loading",
  "app.unavailable.title": "Holdfast couldn't start",
  "app.unavailable.body": "The app couldn't load its settings. Check your connection and try again.",
  "app.retry": "Try again",
  "app.backToFiles": "Back to Files",
  "app.requestId": "req {id}",
  "app.close": "Close",
  "app.cancel": "Cancel",
  "app.continue": "Continue",
  "app.undo": "Undo",
  "app.more": "More",
  "app.comingSoon": "Coming soon",
  "app.preparing": "This page is being prepared.",

  "nav.primary": "Primary",
  "nav.files": "Files",
  "nav.myFiles": "My files",
  "nav.sharedWithMe": "Shared with me",
  "nav.sharedByMe": "Shared by me",
  "nav.shared": "Shared",
  "nav.shared.withMe": "With me",
  "nav.shared.byMe": "By me",
  "nav.recent": "Recent",
  "nav.starred": "Starred",
  "nav.trash": "Trash",
  "nav.account": "Account",
  "nav.admin": "Admin",
  "nav.uploads": "Uploads",
  "nav.search": "Search",
  "nav.storage": "Storage",
  "nav.preview": "Preview",
  "nav.help": "Help",
  "nav.publicLink": "Shared file",
  "nav.home": "Holdfast home",
  "nav.breadcrumb": "Breadcrumb",
  "nav.filesSwitcher": "Switch files view",
  "nav.sharedSwitcher": "Shared files view",

  "header.search": "Search files",
  "header.searchPlaceholder": "Search files",
  "header.searchPlaceholderShort": "Search",
  "header.palette": "Command palette",
  "header.view": "View",
  "header.view.list": "List view",
  "header.view.grid": "Grid view",
  "header.new": "New",
  "header.newFolder": "New folder",
  "header.upload": "Upload files…",
  "header.readOnlyDisabled": "Not available while Holdfast is read-only.",
  "header.uploadsDisabled": "Uploads are paused right now.",

  "user.menu": "Account menu",
  "user.settings": "Account settings",
  "user.storage": "Manage storage",
  "user.help": "Help",
  "user.shortcuts": "Keyboard shortcuts",
  "user.support": "Contact support",
  "user.terms": "Terms",
  "user.privacy": "Privacy",
  "user.dmca": "DMCA",
  "user.signOut": "Sign out",
  "user.theme": "Theme",
  "user.theme.system": "Match system",
  "user.theme.light": "Light",
  "user.theme.dark": "Dark",
  "user.theme.toDark": "Switch to dark mode",
  "user.theme.toLight": "Switch to light mode",

  "storage.label": "Storage",
  "storage.of": "{used} of {quota}",
  "storage.aria": "{used} of {quota} used",
  "storage.loading": "Loading storage use",
  "storage.almostFull": "Almost full",
  "storage.full": "Storage is full",

  "details.label": "Details",
  "details.empty.title": "Nothing selected",
  "details.empty.body": "Select a file or folder to see its details.",

  "banner.readOnly": "Holdfast is read-only for maintenance.",
  "banner.deletion": "This account is scheduled for deletion on {date}. Your links are paused until then.",
  "banner.deletion.cancel": "Cancel deletion",
  "banner.deletion.cancelled": "Deletion cancelled.",
  "banner.deletion.started": "Deletion has already started — contact support.",
  "banner.deletion.failed": "Couldn't cancel the deletion. Try again.",
  "banner.impersonation": "Viewing as {name} — read-only",
  "banner.impersonation.stop": "Stop",

  "toast.rateLimited": "Too many requests. Try again in {seconds} s.",
  "toast.rateLimitedSoon": "Too many requests. Try again shortly.",
  "toast.impersonationReadOnly": "Read-only while impersonating",
  "toast.uploadsPaused": "Uploads are paused right now.",
  "toast.linksPaused": "Link sharing is paused right now.",
  "toast.featurePaused": "This feature is paused right now.",
  "toast.readOnly": "Holdfast is read-only for maintenance.",
  "toast.generic": "Something went wrong. Try again.",
  "toast.dismiss": "Dismiss",

  "selection.count": "{count} selected",
  "selection.clear": "Clear",
  "selection.announce": "{count} selected",
  "selection.none": "Selection cleared",

  "list.name": "Name",
  "list.sharing": "Sharing",
  "list.modified": "Modified",
  "list.size": "Size",
  "list.select": "Select {name}",
  "list.more": "More actions for {name}",
  "list.loadingMore": "Loading more",
  "list.shared.people": "Shared with {count} people",
  "list.shared.person": "Shared with 1 person",
  "list.link.active": "Link on",
  "list.link.paused": "Link paused",
  "list.link.expired": "Link expired",
  "list.folder": "Folder",

  "status.pending": "Scanning",
  "status.infected": "Blocked — flagged by the malware scan",
  "status.underReview": "Under review",
  "status.skipped": "Couldn't scan",
  "status.skipped.size": "Couldn't scan — too large to scan",
  "status.error": "Couldn't scan — try again",

  "ribbon.idle": "No transfers",
  "ribbon.show": "Show details",
  "ribbon.hide": "Hide",
  "ribbon.label": "Transfers",

  "empty.first.title": "Your files live here",
  "empty.first.body": "Drop anything onto this window. Everything is scanned before it can be shared.",
  "empty.cleared.title": "Nothing here",
  "empty.cleared.body": "Drop files here or move some in.",
  "empty.noResults.title": "No files match",
  "empty.noResults.body": "Try fewer words, or search everything you have access to.",
  "empty.unavailable.title": "Couldn't load this",
  "empty.unavailable.body": "The connection dropped. Your files are fine.",

  "placeholder.body": "Coming soon",
  "placeholder.shared.note": "Shared files appear here once sharing is switched on.",

  "notFound.title": "Page not found",
  "notFound.body": "This address doesn't lead anywhere. It may have been moved or removed.",

  "error.title": "Something broke on this page",
  "error.body": "The rest of Holdfast still works. Reload to try again.",
  "error.reload": "Reload",

  "confirm.default": "Confirm",

  "palette.label": "Command palette",
  "palette.placeholder": "Type a command or search",
  "palette.empty": "No commands match",
  "palette.section.selection": "Selection",
  "palette.section.goto": "Go to",
  "palette.section.actions": "Actions",
  "palette.footer.move": "move",
  "palette.footer.run": "run",
  "palette.footer.toggle": "toggle",
  "palette.footer.shortcuts": "Keyboard shortcuts",

  "shortcuts.title": "Keyboard shortcuts",
  "shortcuts.search": "Search",
  "shortcuts.palette": "Command palette",
  "shortcuts.move": "Move through the list",
  "shortcuts.open": "Open",
  "shortcuts.quickLook": "Quick look",
  "shortcuts.selectAll": "Select all",
  "shortcuts.trash": "Move to trash",
  "shortcuts.escape": "Clear selection or close",
  "shortcuts.help": "Show this list",
  "shortcuts.newFolder": "New folder",
  "shortcuts.rename": "Rename",
  "shortcuts.upload": "Upload files",
  "shortcuts.theme": "Switch theme",

  "help.title": "Help",
  "help.body": "Guides and answers live on the Holdfast support page.",
  "help.open": "Open the support page",
  "help.contact": "Contact support",
  "help.contact.body": "Write to us and include the request id shown with any error.",
  "help.legal": "Legal",

  "legal.terms": "Terms",
  "legal.privacy": "Privacy",
  "legal.dmca": "DMCA",
  "legal.support": "Support",
  "legal.footer": "Legal",

  "reauth.title": "Your session ended",
  "reauth.body": "Sign in to continue.",
  "reauth.passkey": "Continue with passkey",
  "reauth.password": "Password",
  "reauth.submit": "Sign in",
  "reauth.signOut": "Sign in as someone else",
  "reauth.failed": "That didn't work. Check your password and try again.",

  "terms.title": "We've updated the Terms and Privacy Policy.",
  "terms.body": "Read the current versions, then accept to keep using Holdfast.",
  "terms.privacyPolicy": "Privacy Policy",
  "terms.readTerms": "Read the Terms",
  "terms.readPrivacy": "Read the Privacy Policy",
  "terms.checkbox": "I agree to the Terms and Privacy Policy.",
  "terms.accept": "Accept and continue",
  "terms.signOut": "Sign out",
  "terms.failed": "Couldn't record your acceptance. Try again.",
  "terms.version": "Version {version}",

  "auth.or": "or",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.name": "Name",
  "auth.passkey": "Continue with passkey",
  "auth.google": "Continue with Google",
  "auth.human": "Checking you're human…",
  "auth.humanFailed": "Couldn't confirm you're human. Reload the page and try again.",
  "auth.humanWait": "Wait for the human check to finish.",
  "auth.notWired": "Sign-in isn't available in this build yet.",
  "auth.error.generic": "That didn't work. Try again.",
  "auth.error.credentials": "Wrong email or password.",
  "auth.error.rate": "Too many attempts. Wait a minute and try again.",
  "auth.error.passkey": "The passkey sign-in didn't complete. Try again or use your password.",

  "login.title": "Sign in",
  "login.submit": "Sign in",
  "login.forgot": "Forgot password?",
  "login.create": "Create an account",
  "login.suspended": "This account is suspended. Contact support.",
  "login.verified": "Email confirmed. Sign in to continue.",
  "login.reset": "Password changed. Sign in with the new one.",

  "signup.title": "Create your account",
  "signup.invite.note": "Holdfast is in a private beta — you'll need an invite code.",
  "signup.invite": "Invite code",
  "signup.invite.valid": "This invite is valid.",
  "signup.invite.invalid": "This invite can't be used. Check the code or ask for a new one.",
  "signup.password.help": "12 characters or more; we check it against known breaches.",
  "signup.password.strength.0": "Too short",
  "signup.password.strength.1": "Weak",
  "signup.password.strength.2": "Fair",
  "signup.password.strength.3": "Good",
  "signup.password.strength.4": "Strong",
  "signup.password.breached": "This password appears in a known breach. Choose another.",
  "signup.birth": "Birth month and year",
  "signup.birth.month": "Month",
  "signup.birth.year": "Year",
  "signup.birth.note": "Used once to check you're 13 or older; we don't keep it.",
  "signup.assent.before": "I agree to the ",
  "signup.assent.and": " and ",
  "signup.assent.after": ".",
  "signup.submit": "Create account",
  "signup.have": "Already have an account? Sign in",
  "signup.error.name": "Enter your name.",
  "signup.error.email": "Enter a valid email address.",
  "signup.error.password": "Use 12 characters or more.",
  "signup.error.passwordLong": "Use 128 characters or fewer.",
  "signup.error.invite": "Enter your invite code.",
  "signup.error.birth": "Enter the month (1–12) and a four-digit year.",
  "signup.error.age": "You need to be 13 or older to use Holdfast.",
  "signup.error.assent": "You need to accept the Terms and Privacy Policy.",

  "verify.title": "Check your email",
  "verify.body.before": "We sent a link to ",
  "verify.body.after": ". It works for one hour.",
  "verify.body.unknown": "We sent you a link. It works for one hour.",
  "verify.resend": "Send it again",
  "verify.resend.in": "(in {time})",
  "verify.resent": "Sent. Check your inbox.",
  "verify.resend.failed": "Couldn't send the email. Try again in a minute.",
  "verify.change": "Wrong address? Change it",
  "verify.change.label": "New email address",
  "verify.change.submit": "Update and resend",
  "verify.change.done": "Updated. We sent a link to the new address.",
  "verify.change.failed": "Couldn't change the address. Check it and try again.",
  "verify.signOut": "Sign out",

  "forgot.title": "Reset your password",
  "forgot.body": "Enter your email and we'll send a link to choose a new password.",
  "forgot.submit": "Send reset link",
  "forgot.sent": "If that address has an account, a reset link is on its way. It works for one hour.",
  "forgot.back": "Back to sign in",

  "reset.title": "Choose a new password",
  "reset.new": "New password",
  "reset.submit": "Change password",
  "reset.missing": "This reset link is incomplete. Request a new one.",
  "reset.failed": "This reset link has expired or was already used. Request a new one.",

  "twoFactor.title": "Enter your code",
  "twoFactor.body": "From your authenticator app.",
  "twoFactor.code": "Six-digit code",
  "twoFactor.backup.title": "Enter a backup code",
  "twoFactor.backup.body": "Each backup code works once.",
  "twoFactor.backup.code": "Backup code",
  "twoFactor.trust": "Trust this device for 30 days",
  "twoFactor.useBackup": "Use a backup code instead",
  "twoFactor.useTotp": "Use the authenticator app instead",
  "twoFactor.failed": "That code didn't work. Check it and try again.",
  "twoFactor.error.code": "Enter the six digits from your app.",
  "twoFactor.error.backup": "Enter a backup code.",

  "invite.checking": "Checking your invite",
} as const;

export type MessageKey = keyof typeof en;
